### ISSUE TITLE
Stop compiling, just using upstream binary?

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/arm-machine#8]
Beginning with 0.9.0 the docker/machine repo has ARM binary of docker-machine in the GitHub release page.

Should we stop building the binary and just download the binary from GitHub release and put it into the deb package?

ping @DieterReuter

**Comment by atomi** [comment]
I'd prefer just the binaries for what it's worth. I'm on an arch linux for the rpi.

**Comment by DieterReuter** [comment]
Good idea!

**Comment by StefanScherer** [comment]
Done
